platform :ios, '11.0'
inhibit_all_warnings!

target 'PerfectEar' do
  use_frameworks!

  # Pods for PerfectEar
  pod 'Fabric'
  pod 'Crashlytics'
  
  target 'PerfectEarTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
